// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFx5dPSmmE-PuNl6cSxm0lPqrGUy26S_Q',
    appId: '1:1019794168544:web:1cfa2912b2551b90564e85',
    messagingSenderId: '1019794168544',
    projectId: 'whatsappclonepractice-61afc',
    authDomain: 'whatsappclonepractice-61afc.firebaseapp.com',
    storageBucket: 'whatsappclonepractice-61afc.firebasestorage.app',
    measurementId: 'G-XE8H2YNTZB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDvQvZRATiYcttM9QjzYQ2KqG4GXFF3FW0',
    appId: '1:1019794168544:android:b2aaec413055cd5a564e85',
    messagingSenderId: '1019794168544',
    projectId: 'whatsappclonepractice-61afc',
    storageBucket: 'whatsappclonepractice-61afc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXle-g8ld1Zlc9G1wA9lymaczBlAEx99w',
    appId: '1:1019794168544:ios:2c3096944b90c9ce564e85',
    messagingSenderId: '1019794168544',
    projectId: 'whatsappclonepractice-61afc',
    storageBucket: 'whatsappclonepractice-61afc.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClonePractice',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXle-g8ld1Zlc9G1wA9lymaczBlAEx99w',
    appId: '1:1019794168544:ios:2c3096944b90c9ce564e85',
    messagingSenderId: '1019794168544',
    projectId: 'whatsappclonepractice-61afc',
    storageBucket: 'whatsappclonepractice-61afc.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClonePractice',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFx5dPSmmE-PuNl6cSxm0lPqrGUy26S_Q',
    appId: '1:1019794168544:web:48e1fbf9c5eafa66564e85',
    messagingSenderId: '1019794168544',
    projectId: 'whatsappclonepractice-61afc',
    authDomain: 'whatsappclonepractice-61afc.firebaseapp.com',
    storageBucket: 'whatsappclonepractice-61afc.firebasestorage.app',
    measurementId: 'G-E9ZLR0ZG0K',
  );
}
